# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djusername', models.CharField(max_length=50, verbose_name='党建云用户名')),
                ('djpasswd', models.CharField(max_length=50, verbose_name='党建云密码')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
