# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0002_djuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djusername', models.CharField(max_length=50, verbose_name='党建云用户名')),
                ('djpasswd', models.CharField(max_length=50, verbose_name='党建云密码')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.DeleteModel(
            name='DjUser',
        ),
    ]
