# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0003_auto_20180319_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='djinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dangjiansite.DjInfo', verbose_name='党建信息'),
            preserve_default=False,
        ),
    ]
