# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0004_auto_20180319_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='djinfo',
        ),
        migrations.AddField(
            model_name='djinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
    ]
