# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0006_auto_20180319_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='djinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dangjiansite.DjInfo', verbose_name='党建信息'),
        ),
    ]
