# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0007_auto_20180319_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRsult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_day', models.CharField(default='20180319', max_length=50, verbose_name='创建日期')),
                ('thumb', models.CharField(max_length=50, verbose_name='信息评论')),
                ('view', models.CharField(max_length=50, verbose_name='党员视角发布')),
                ('hlep', models.CharField(max_length=50, verbose_name='互助广场回答')),
                ('exam', models.CharField(max_length=50, verbose_name='在线知识竞答')),
                ('study1', models.CharField(max_length=50, verbose_name='在线阅读学习资料')),
                ('study2', models.CharField(max_length=50, verbose_name='学习资料写体会')),
                ('conLogin', models.CharField(max_length=50, verbose_name='连续登录')),
                ('mobileLogin', models.CharField(max_length=50, verbose_name='手机端登录')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
