# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0008_dailyrsult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyRsult',
            new_name='DailyResult',
        ),
    ]
