# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0009_auto_20180319_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyresult',
            name='create_day',
            field=models.CharField(default='2018年03月19日', max_length=50, verbose_name='创建日期'),
        ),
    ]
