# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0010_auto_20180319_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_day', models.CharField(default='2018年03月19日', max_length=50, verbose_name='创建日期')),
                ('thumbDetail', models.TextField(max_length=500, verbose_name='信息评论详细')),
                ('viewDetail', models.TextField(max_length=500, verbose_name='党员视角发布详细')),
                ('hlepDetail', models.TextField(max_length=500, verbose_name='互助广场回答详细')),
                ('examDetail', models.TextField(max_length=500, verbose_name='在线知识竞答详细')),
                ('study1Detail', models.TextField(max_length=500, verbose_name='在线阅读学习资料详细')),
                ('study2Detail', models.TextField(max_length=500, verbose_name='学习资料写体会详细')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
