# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0012_auto_20180319_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_day', models.CharField(default='2018-03-19', max_length=50, verbose_name='创建日期')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
