# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0013_errlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='create_day',
            field=models.CharField(default='2018-03-20', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='dailydetail',
            name='examDetail',
            field=models.TextField(default='', max_length=500, verbose_name='在线知识竞答详细'),
        ),
        migrations.AlterField(
            model_name='dailydetail',
            name='hlepDetail',
            field=models.TextField(default='', max_length=500, verbose_name='互助广场回答详细'),
        ),
        migrations.AlterField(
            model_name='dailydetail',
            name='study1Detail',
            field=models.TextField(default='', max_length=500, verbose_name='在线阅读学习资料详细'),
        ),
        migrations.AlterField(
            model_name='dailydetail',
            name='study2Detail',
            field=models.TextField(default='', max_length=500, verbose_name='学习资料写体会详细'),
        ),
        migrations.AlterField(
            model_name='dailydetail',
            name='thumbDetail',
            field=models.TextField(default='', max_length=500, verbose_name='信息评论详细'),
        ),
        migrations.AlterField(
            model_name='dailydetail',
            name='viewDetail',
            field=models.TextField(default='', max_length=500, verbose_name='党员视角发布详细'),
        ),
        migrations.AlterField(
            model_name='dailyresult',
            name='create_day',
            field=models.CharField(default='2018-03-20', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='errlog',
            name='create_day',
            field=models.CharField(default='2018-03-20', max_length=50, verbose_name='创建日期'),
        ),
    ]
