# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0016_thumblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='djinfo',
            new_name='idjinfo',
        ),
        migrations.AddField(
            model_name='djinfo',
            name='iuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
