# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0017_auto_20180320_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydetail',
            name='create_time',
            field=models.CharField(default='%% 203255', max_length=50, verbose_name='创建日期'),
        ),
    ]
