# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0018_dailydetail_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='create_time',
            field=models.CharField(default='20:33:48', max_length=50, verbose_name='创建日期'),
        ),
    ]
