# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0019_auto_20180320_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydetail',
            name='create_time',
        ),
    ]
