# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0020_remove_dailydetail_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumblog',
            name='user',
        ),
        migrations.AddField(
            model_name='thumblog',
            name='idjinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dangjiansite.DjInfo', verbose_name='党建用户'),
        ),
    ]
