# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0021_auto_20180320_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_day', models.CharField(default='2018-03-20', max_length=50, verbose_name='创建日期')),
                ('subjectId', models.CharField(max_length=50, verbose_name='题目id')),
                ('title', models.CharField(max_length=500, verbose_name='题目名称')),
                ('detail', models.TextField(max_length=500, verbose_name='详细')),
                ('idjinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dangjiansite.DjInfo', verbose_name='党建用户')),
            ],
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_day', models.CharField(default='2018-03-20', max_length=50, verbose_name='创建日期')),
                ('question', models.TextField(max_length=500, verbose_name='问题')),
                ('answer', models.CharField(max_length=50, verbose_name='答案')),
                ('answerText', models.CharField(max_length=50, verbose_name='文本答案')),
                ('idjinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dangjiansite.DjInfo', verbose_name='党建用户')),
            ],
        ),
    ]
