# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0023_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='create_day',
            field=models.CharField(default='2018-03-21', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='dailyresult',
            name='create_day',
            field=models.CharField(default='2018-03-21', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='errlog',
            name='create_day',
            field=models.CharField(default='2018-03-21', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='examdetail',
            name='create_day',
            field=models.CharField(default='2018-03-21', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='create_day',
            field=models.CharField(default='2018-03-21', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='thumblog',
            name='create_day',
            field=models.CharField(default='2018-03-21', max_length=50, verbose_name='创建日期'),
        ),
    ]
