# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0024_auto_20180321_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dailyresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='errlog',
            name='user',
        ),
        migrations.AddField(
            model_name='dailydetail',
            name='idjinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dangjiansite.DjInfo', verbose_name='党建用户'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='idjinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dangjiansite.DjInfo', verbose_name='党建用户'),
        ),
        migrations.AddField(
            model_name='errlog',
            name='idjinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dangjiansite.DjInfo', verbose_name='党建用户'),
        ),
    ]
