# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0025_auto_20180321_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errlog',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='内容'),
        ),
    ]
