# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0028_auto_20180322_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='create_day',
            field=models.CharField(default='2018-03-23', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='dailyresult',
            name='create_day',
            field=models.CharField(default='2018-03-23', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='errlog',
            name='create_day',
            field=models.CharField(default='2018-03-23', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='examdetail',
            name='create_day',
            field=models.CharField(default='2018-03-23', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='create_day',
            field=models.CharField(default='2018-03-23', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='create_time',
            field=models.CharField(default='13:16:25', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='helpinfo',
            name='create_day',
            field=models.CharField(default='2018-03-23', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='helpinfo',
            name='create_time',
            field=models.CharField(default='13:16:25', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='studyinfo',
            name='create_day',
            field=models.CharField(default='2018-03-23', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='studyinfo',
            name='create_time',
            field=models.CharField(default='13:16:25', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='thumbinfo',
            name='create_day',
            field=models.CharField(default='2018-03-23', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='thumbinfo',
            name='create_time',
            field=models.CharField(default='13:16:25', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='thumblog',
            name='create_day',
            field=models.CharField(default='2018-03-23', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='viewinfo',
            name='create_day',
            field=models.CharField(default='2018-03-23', max_length=50, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='viewinfo',
            name='create_time',
            field=models.CharField(default='13:16:25', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='viewinfo',
            name='pub_content',
            field=models.TextField(max_length=500, verbose_name='发布内容'),
        ),
    ]
