# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangjiansite', '0029_auto_20180323_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='create_time',
            field=models.CharField(default='23:25:10', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='helpinfo',
            name='create_time',
            field=models.CharField(default='23:25:10', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='studyinfo',
            name='create_time',
            field=models.CharField(default='23:25:10', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='thumbinfo',
            name='create_time',
            field=models.CharField(default='23:25:10', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='viewinfo',
            name='create_time',
            field=models.CharField(default='23:25:10', max_length=50, verbose_name='创建时间'),
        ),
    ]
